### ISSUE TITLE
Consonant sign NG (amisara) should be above the letter, not vowel, in "letter+vowel+amisara" combination

### ISSUE THREAD

**Issue by bennylin** [notofonts/batak#8]
### Title 
Consonant sign NG (amisara) should be above the letter, not vowel, in "letter+vowel+amisara" combination
  > Writing this bug report on behalf of https://incubator.wikimedia.org/wiki/User_talk:Surung_Simanullang

### Font 
NotoSansBatak-Regular.ttf

[NotoSansBatak-Regular.zip](https://github.com/notofonts/batak/files/12004087/NotoSansBatak-Regular.zip)

### Where the font came from, and when
I believe from https://fonts.google.com/noto/specimen/Noto+Sans+Batak, that's where I usually download Noto fonts from. But I'm not 100% sure.

Date: 2021-04-01 (according to the file date on my folder)

### Font Version
* Win -- 3.1, August 2, 2020

### Issue
  > Summarize the issue briefly -- one paragraph preferred

In combination like 'ing ong ung bing bong bung', etc, where the combination of letter+vowel+amisara is formed, currently the amisara is positioned above the vowel, while it should be positioned above the letter instead.

### Character data
* translit: bing bong bung ding dong dung ging gong gung
* syllables: ᯅᯪᯰ ᯅᯬᯰ ᯅᯮᯰ ᯑᯪᯰ ᯑᯬᯰ ᯑᯮᯰ ᯎᯪᯰ ᯎᯬᯰ ᯎᯮᯰ
* characters: ᯅ ᯪ ᯰ ᯅ ᯬ ᯰ ᯅ ᯮ ᯰ ᯑ ᯪ ᯰ ᯑ ᯬ ᯰ ᯑ ᯮ ᯰ ᯎ ᯪ ᯰ ᯎ ᯬ ᯰ ᯎ ᯮ ᯰ
** consonants: 1BC5 ᯅ BATAK LETTER BA, 1BD1 ᯑ BATAK LETTER DA, 1BCE ᯎ BATAK LETTER GA 
** 1BEA ᯪ BATAK VOWEL SIGN I = ulua, 1BEC ᯬ BATAK VOWEL SIGN O = siala ulu, 1BEE ᯮ BATAK VOWEL SIGN U = boruta 
** 1BF0 ᯰ BATAK CONSONANT SIGN NG = amisara 

### Screenshot
  > If possible, include a screenshot or an image illustrating the issue.
  > Annotations are also helpful.

![image](https://github.com/notofonts/batak/assets/3002108/5593901b-cab7-4dd4-816e-89cc1b16f37e)
Image 1: what it should look like: ang eng ing ong ung beng bing bong bung ceng cing cong cung deng ding dong dung geng ging gong gung dst sampai nyung

![image](https://github.com/notofonts/batak/assets/3002108/c57336ef-3692-404a-9085-387120b0d626)
Image 2: what it currently look like: ᯅᯪᯰ ᯅᯬᯰ ᯅᯮᯰ ᯑᯪᯰ ᯑᯬᯰ ᯑᯮᯰ ᯎᯪᯰ ᯎᯬᯰ ᯎᯮᯰ

![image](https://github.com/notofonts/batak/assets/3002108/5b1f23e4-0376-40b1-bb39-2ace0408f115)
Image 3: Add MSS 15678, text 2 "ᯅᯮᯀᯖ᯲ ᯘᯖᯰᯖᯪᯰ ᯞᯮᯂᯮᯄ᯦᯲ ᯇᯝᯖᯂᯮᯖ᯲ ᯉᯪ ᯅᯮᯞᯉ᯲" translit "buat satangting luhuk pangatahut ni bulan" shows that in "satangting", the amisara is on top of consonant letter "ta", not the vowel letter "i".

**Comment by simoncozens** [comment]
I've fixed this so that post-base vowels and ng-signs are swapped around:

```
$ shape master_ttf/NotoSansBatak-Regular.ttf ' ᯅᯪᯰ ᯅᯬᯰ'
[space=0+260|babatak=1+1080|ngSignbatak=1@-238,48+0|iSignbatak=1+483|space=4+260|babatak=5+1080|ngSignbatak=5@-238,48+0|oSignbatak=5+533]
```
![shape](https://github.com/notofonts/batak/assets/106728/3ce1fed2-d469-49a3-a6bf-4a63d83ca792)

**Comment by bennylin** [comment]
Thanks on behalf of Mandailing community!

**Comment by dscorbett** [comment]
[L2/08-011R](https://www.unicode.org/L2/L2008/08011r-n3320r-batak.pdf) says “The consonant signs ◌ᯰ CONSONANT SIGN NG and ◌ᯱ CONSONANT SIGN H are usually rendered above the spacing vowels ◌ᯧ VOWEL SIGN E, ◌ᯪ VOWEL SIGN I, ◌ᯫ VOWEL SIGN KARO I, and ◌ᯬ VOWEL SIGN O”, with examples in some figures. What is the correct positioning? Does it depend on the language? Should <i>-h</i> be repositioned the same as <i>-ng</i>?
